export enum UserRole {
  STUDENT = 'STUDENT',
  KAFEDRA = 'KAFEDRA',
  DEKANAT = 'DEKANAT',
  ADMIN = 'ADMIN',
}

export enum DocumentStatus {
  PENDING = 'PENDING',
  KAFEDRA_APPROVED = 'KAFEDRA_APPROVED',
  DEKANAT_APPROVED = 'DEKANAT_APPROVED',
  REJECTED = 'REJECTED',
}
