/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace DiplomaRegistry {
  export type DocumentRecordStruct = {
    documentId: string;
    hash: BytesLike;
    issuer: AddressLike;
    timestamp: BigNumberish;
    status: BigNumberish;
    exists: boolean;
  };

  export type DocumentRecordStructOutput = [
    documentId: string,
    hash: string,
    issuer: string,
    timestamp: bigint,
    status: bigint,
    exists: boolean
  ] & {
    documentId: string;
    hash: string;
    issuer: string;
    timestamp: bigint;
    status: bigint;
    exists: boolean;
  };
}

export interface DiplomaRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "emitActionEvent"
      | "getDocument"
      | "logEvent"
      | "registerDocument"
      | "verifyDocument"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ActionEmitted"
      | "DocumentRegistered"
      | "StageLogged"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "emitActionEvent",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "getDocument", values: [string]): string;
  encodeFunctionData(
    functionFragment: "logEvent",
    values: [string, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerDocument",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyDocument",
    values: [string, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "emitActionEvent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDocument",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "logEvent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerDocument",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyDocument",
    data: BytesLike
  ): Result;
}

export namespace ActionEmittedEvent {
  export type InputTuple = [
    documentId: string,
    actionType: string,
    actor: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    documentId: string,
    actionType: string,
    actor: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    documentId: string;
    actionType: string;
    actor: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DocumentRegisteredEvent {
  export type InputTuple = [
    documentId: string,
    hash: BytesLike,
    issuer: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    documentId: string,
    hash: string,
    issuer: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    documentId: string;
    hash: string;
    issuer: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StageLoggedEvent {
  export type InputTuple = [
    documentId: string,
    hash: BytesLike,
    actor: AddressLike,
    status: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    documentId: string,
    hash: string,
    actor: string,
    status: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    documentId: string;
    hash: string;
    actor: string;
    status: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DiplomaRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): DiplomaRegistry;
  waitForDeployment(): Promise<this>;

  interface: DiplomaRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  emitActionEvent: TypedContractMethod<
    [documentId: string, actionType: string],
    [void],
    "nonpayable"
  >;

  getDocument: TypedContractMethod<
    [documentId: string],
    [DiplomaRegistry.DocumentRecordStructOutput],
    "view"
  >;

  logEvent: TypedContractMethod<
    [documentId: string, hash: BytesLike, status: BigNumberish],
    [void],
    "nonpayable"
  >;

  registerDocument: TypedContractMethod<
    [documentId: string, hash: BytesLike],
    [void],
    "nonpayable"
  >;

  verifyDocument: TypedContractMethod<
    [documentId: string, hash: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "emitActionEvent"
  ): TypedContractMethod<
    [documentId: string, actionType: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getDocument"
  ): TypedContractMethod<
    [documentId: string],
    [DiplomaRegistry.DocumentRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "logEvent"
  ): TypedContractMethod<
    [documentId: string, hash: BytesLike, status: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerDocument"
  ): TypedContractMethod<
    [documentId: string, hash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyDocument"
  ): TypedContractMethod<
    [documentId: string, hash: BytesLike],
    [boolean],
    "view"
  >;

  getEvent(
    key: "ActionEmitted"
  ): TypedContractEvent<
    ActionEmittedEvent.InputTuple,
    ActionEmittedEvent.OutputTuple,
    ActionEmittedEvent.OutputObject
  >;
  getEvent(
    key: "DocumentRegistered"
  ): TypedContractEvent<
    DocumentRegisteredEvent.InputTuple,
    DocumentRegisteredEvent.OutputTuple,
    DocumentRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "StageLogged"
  ): TypedContractEvent<
    StageLoggedEvent.InputTuple,
    StageLoggedEvent.OutputTuple,
    StageLoggedEvent.OutputObject
  >;

  filters: {
    "ActionEmitted(string,string,address,uint256)": TypedContractEvent<
      ActionEmittedEvent.InputTuple,
      ActionEmittedEvent.OutputTuple,
      ActionEmittedEvent.OutputObject
    >;
    ActionEmitted: TypedContractEvent<
      ActionEmittedEvent.InputTuple,
      ActionEmittedEvent.OutputTuple,
      ActionEmittedEvent.OutputObject
    >;

    "DocumentRegistered(string,bytes32,address,uint256)": TypedContractEvent<
      DocumentRegisteredEvent.InputTuple,
      DocumentRegisteredEvent.OutputTuple,
      DocumentRegisteredEvent.OutputObject
    >;
    DocumentRegistered: TypedContractEvent<
      DocumentRegisteredEvent.InputTuple,
      DocumentRegisteredEvent.OutputTuple,
      DocumentRegisteredEvent.OutputObject
    >;

    "StageLogged(string,bytes32,address,uint8,uint256)": TypedContractEvent<
      StageLoggedEvent.InputTuple,
      StageLoggedEvent.OutputTuple,
      StageLoggedEvent.OutputObject
    >;
    StageLogged: TypedContractEvent<
      StageLoggedEvent.InputTuple,
      StageLoggedEvent.OutputTuple,
      StageLoggedEvent.OutputObject
    >;
  };
}
