/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DiplomaRegistry } from "./DiplomaRegistry";
export * as factories from "./factories";
export { DiplomaRegistry__factory } from "./factories/DiplomaRegistry__factory";
